services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram-bot-full-version.py "
    repo: "https://github.com/radomir4ik26/reportbot"
    branch: "main"
    envVars:
      - key: BOT_TOKEN
        sync: false
